title: super16.github.io

url: https://super16.github.io

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

collections:
  notes:
    output: true
    permalink: /:collection/:slug

plugins:
  - jekyll-sitemap

exclude:
  - 'README.md'
